name: pipeline

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: Linux
    steps:
      - name: recuperer le code
        uses: actions/checkout@v4
      - name:  configurer python
        uses: actions/checkout@v5
        with:
          python-version: '3.10'
      - name: afficher un message
        run: echo ' Mon premier workflow github actions fonctionne !'
